"""empty message

Revision ID: 7d9505c0a5d1
Revises: 
Create Date: 2020-11-13 18:30:03.579354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9505c0a5d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Klang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('mp3', sa.String(length=100), nullable=False),
    sa.Column('transcription', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mp3'),
    sa.UniqueConstraint('user')
    )
    op.drop_table('widget')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget',
    sa.Column('widget_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('widget_id')
    )
    op.drop_table('Klang')
    # ### end Alembic commands ###
