name: deploy
on: 
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Access to server
      uses: appleboy/ssh-action@v0.1.10
      with: 
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            cd /home/arborator/arborator-backend
            git pull origin main
            source venv/bin/activate
            pip3 install -r requirements.txt
            pip3 install uWSGI==2.0.22
            flask db upgrade
            sudo systemctl restart arborator-backend.service


