name: deploy
on: 
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, arborator-host]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Access to repository and run the instructions 
      run: |
        cd arborator-backend
        git pull origin main 
        source venv/bin/activate
        pip3 install -r requirements.txt    
        sudo systemctl restart arborator-backend.service 
    